# Dcokerfile: openssh-server,nginx-1.16.1,java-1.8.0_231

#Base Images
FROM busybox:latest

WORKDIR /download
RUN wget https://github.com/alibaba/nacos/releases/download/2.0.3/nacos-server-2.0.2.tar.gz


CMD ["/bin/sh","-c","sleep 18000"]

