# Dcokerfile: openssh-server,nginx-1.16.1,java-1.8.0_231

#Base Images
FROM busybox:latest

WORKDIR /download
RUN wget registry.k8s.io/descheduler/descheduler:v0.27.1


CMD ["/bin/sh","-c","sleep 18000"]

